sudo: false

language: elixir

elixir:
  - 1.2.5
  - 1.3.0

otp_release:
  - 18.3
  - 19.0

cache:
  directories:
    - $HOME/.hex

before_install:
  - kerl list installations
  - export MIX_ENV=ci

script: mix espec

after_success:
  - mix coveralls.travis

after_script:
  - mix inch.report
  - mix xref warnings
  - mix xref unreachable
  - mix credo --strict
  - mix hex.outdated
