sudo: false

language: elixir

elixir:
  - 1.2.3

otp_release:
  - 18.2

cache:
  directories:
    - $HOME/.hex

before_install:
  - kerl list installations
  - export MIX_ENV=ci

script: mix espec

after_success:
  - mix coveralls.travis

after_script:
  - mix inch.report
  - mix dogma
  - mix credo --strict
  - mix hex.outdated
